[package]
name = "gateway"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]

crossbeam-channel.workspace = true

eyre.workspace = true
pc-common.workspace = true
pc-proposer.workspace = true
pc-rpc.workspace = true
pc-sequencer.workspace = true
serde_json.workspace = true

# Async / Threads
tokio.workspace = true
tracing.workspace = true
